name: PokemonPlugin
version: '${version}'
main: com.dreamer.pokemonmod.PokemonPlugin
api-version: 1.16
authors: [ Birdream ]
description: 포켓몬 플러그인
commands:
  포켓몬설정:
    description: 포켓몬의 설정 명령어를 한글화한 명령어입니다.
    usage: /<command>
    aliases:
      - vhzptahstjfwjd
